spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ovz1.slava-rossii.n0ykp.vps.myjino.ru:49211/night_watch?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
#      hibernate.temp.use_jdbc_metadata_defaults: false

  kafka:
    bootstrap-servers: localhost:9092

  profiles:
    active: default

server:
  port: 8081